/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ScvSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
    interface ScvTooltip {
        "message": string;
        "title": string;
    }
}
declare global {
    interface HTMLScvSideDrawerElement extends Components.ScvSideDrawer, HTMLStencilElement {
    }
    var HTMLScvSideDrawerElement: {
        prototype: HTMLScvSideDrawerElement;
        new (): HTMLScvSideDrawerElement;
    };
    interface HTMLScvTooltipElement extends Components.ScvTooltip, HTMLStencilElement {
    }
    var HTMLScvTooltipElement: {
        prototype: HTMLScvTooltipElement;
        new (): HTMLScvTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "scv-side-drawer": HTMLScvSideDrawerElement;
        "scv-tooltip": HTMLScvTooltipElement;
    }
}
declare namespace LocalJSX {
    interface ScvSideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface ScvTooltip {
        "message"?: string;
        "title"?: string;
    }
    interface IntrinsicElements {
        "scv-side-drawer": ScvSideDrawer;
        "scv-tooltip": ScvTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "scv-side-drawer": LocalJSX.ScvSideDrawer & JSXBase.HTMLAttributes<HTMLScvSideDrawerElement>;
            "scv-tooltip": LocalJSX.ScvTooltip & JSXBase.HTMLAttributes<HTMLScvTooltipElement>;
        }
    }
}
