/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ScvSideDrawer {
    }
}
declare global {
    interface HTMLScvSideDrawerElement extends Components.ScvSideDrawer, HTMLStencilElement {
    }
    var HTMLScvSideDrawerElement: {
        prototype: HTMLScvSideDrawerElement;
        new (): HTMLScvSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "scv-side-drawer": HTMLScvSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface ScvSideDrawer {
    }
    interface IntrinsicElements {
        "scv-side-drawer": ScvSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "scv-side-drawer": LocalJSX.ScvSideDrawer & JSXBase.HTMLAttributes<HTMLScvSideDrawerElement>;
        }
    }
}
